<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.schemebridge</groupId>
    <artifactId>schemebridge-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>schemebridge-parent</name>
    <description>SchemeBridge Multi-Module Aggregator</description>

    <modules>
        <module>schemebridge-auth-service</module>
        <module>schemebridge-scheme-service</module>
    </modules>
</project>
