server:
  port: 8087
  shutdown: graceful
  servlet:
    context-path: /

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost


spring:
  application:
    name: admin-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${SPRING_DATASOURCE_USERNAME:system}
    password: ${SPRING_DATASOURCE_PASSWORD:system}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS:oracle.jdbc.OracleDriver}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      connection-test-query: SELECT 1 FROM DUAL

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

schemebridge:
  admin:
    scheduler:
      cleanup-cron: "0 0 2 * * *"     # 2 AM daily
      stats-cron: "0 */15 * * * *"    # Every 15 mins
      announcement-cron: "0 0 * * * *" # Hourly

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
