package com.schemebridge.notificationservice.enums;

public enum NotificationType {
    APPLICATION_STATUS,
    APPLICATION_SUBMITTED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,
    DOCUMENT_REQUIRED,
    NEW_SCHEME,
    SCHEME_CREATED,
    SCHEME_UPDATED,
    SCHEME_DEADLINE_UPDATE,
    SCHEME_MATCHED,
    ANNOUNCEMENT,
    GRIEVANCE_UPDATED,
    OTP,
    PASSWORD_RESET,
    ACCOUNT_SECURITY,
    GENERAL
}
