package com.schemebridge.config;

import com.schemebridge.entity.Scheme;
import com.schemebridge.enums.SchemeStatus;
import com.schemebridge.enums.SchemeType;
import com.schemebridge.repository.SchemeRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Component
@RequiredArgsConstructor
@Slf4j
public class SchemeDataSeeder implements CommandLineRunner {

    private final SchemeRepository schemeRepository;

    @Override
    public void run(String... args) {
        if (schemeRepository.count() > 0) {
            log.info("Schemes collection is already populated (count: {}). Skipping seeder.", schemeRepository.count());
            return;
        }

        log.info("Seeding realistic Government Schemes into MongoDB...");

        List<Scheme> seedSchemes = List.of(
                // 1. PM-KISAN
                Scheme.builder()
                        .schemeName("Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)")
                        .schemeCode("PM-KISAN-001")
                        .shortDescription("Direct income support of ₹6,000 per year to small and marginal farmer families.")
                        .description("PM-KISAN is a Central Sector Scheme providing financial assistance of ₹6,000 per annum in three equal installments to cultivable landholding farmer families across the country.")
                        .category("Agriculture")
                        .subcategory("Income Support")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(18)
                        .maximumAge(75)
                        .maximumIncome(new BigDecimal("300000"))
                        .allowedGenders(List.of("ALL"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("Farmer", "Agricultural Worker", "Self-Employed"))
                        .requiredDocuments(List.of("Aadhaar Card", "Land Holding Certificate", "Bank Account Passbook"))
                        .benefits(List.of("₹6,000 annual income transfer directly into bank account", "Distributed in 3 installments of ₹2,000 every 4 months"))
                        .websiteUrl("https://pmkisan.gov.in")
                        .applicationMode("ONLINE")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(10)
                        .tags(List.of("Agriculture", "Farmer", "Income", "Central"))
                        .viewCount(1240L)
                        .recommendationCount(850L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 2. PMAY
                Scheme.builder()
                        .schemeName("Pradhan Mantri Awas Yojana (PMAY-Urban/Gramin)")
                        .schemeCode("PMAY-HOUSING-002")
                        .shortDescription("Housing for All initiative offering credit-linked interest subsidy up to ₹2.67 Lakhs.")
                        .description("PMAY provides financial subsidy to Economically Weaker Sections (EWS), Low Income Groups (LIG), and Middle Income Groups (MIG) for constructing or purchasing their first pucca house.")
                        .category("Housing")
                        .subcategory("Affordable Housing")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(21)
                        .maximumAge(70)
                        .maximumIncome(new BigDecimal("600000"))
                        .allowedGenders(List.of("ALL"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("ALL"))
                        .requiredDocuments(List.of("Aadhaar Card", "Income Certificate", "Ration Card", "Property Documents"))
                        .benefits(List.of("Interest subsidy up to ₹2.67 Lakhs on home loans", "Financial assistance for house construction in rural areas"))
                        .websiteUrl("https://pmaymis.gov.in")
                        .applicationMode("HYBRID")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(9)
                        .tags(List.of("Housing", "Home Loan", "Subsidy", "EWS"))
                        .viewCount(980L)
                        .recommendationCount(620L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 3. Ayushman Bharat
                Scheme.builder()
                        .schemeName("Ayushman Bharat - PM Jan Arogya Yojana (PM-JAY)")
                        .schemeCode("PMJAY-HEALTH-003")
                        .shortDescription("Health insurance cover of ₹5 Lakhs per family per year for secondary and tertiary care hospitalization.")
                        .description("PM-JAY is the world's largest health assurance scheme aimed at providing health cover of ₹5 Lakhs per family per year for secondary and tertiary care hospitalization to over 12 crore poor and vulnerable families.")
                        .category("Healthcare")
                        .subcategory("Health Insurance")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(0)
                        .maximumAge(110)
                        .maximumIncome(new BigDecimal("250000"))
                        .allowedGenders(List.of("ALL"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("ALL"))
                        .requiredDocuments(List.of("Aadhaar Card", "Ration Card", "Ayushman Card"))
                        .benefits(List.of("Cashless hospitalization up to ₹5 Lakhs annually", "Covers 1,949 medical procedures in empanelled hospitals"))
                        .websiteUrl("https://pmjay.gov.in")
                        .applicationMode("ONLINE")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(10)
                        .tags(List.of("Health", "Insurance", "Hospitalization", "Medical"))
                        .viewCount(2100L)
                        .recommendationCount(1400L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 4. PM Mudra Yojana
                Scheme.builder()
                        .schemeName("Pradhan Mantri MUDRA Yojana (PMMY)")
                        .schemeCode("PMMY-LOAN-004")
                        .shortDescription("Collateral-free business loans up to ₹10 Lakhs for micro and small enterprises.")
                        .description("PMMY provides institutional credit up to ₹10 Lakhs to non-corporate, non-farm small/micro enterprises across Shishu (up to ₹50k), Kishore (₹50k-₹5L), and Tarun (₹5L-₹10L) categories.")
                        .category("Business & Finance")
                        .subcategory("Micro Loans")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(18)
                        .maximumAge(65)
                        .allowedGenders(List.of("ALL"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("Self-Employed", "Business Owner", "Artisan", "Trader"))
                        .requiredDocuments(List.of("Aadhaar Card", "PAN Card", "Business Registration Proof", "Bank Statement"))
                        .benefits(List.of("Collateral-free loans up to ₹10 Lakhs", "Low interest rates with affordable EMI repayment terms"))
                        .websiteUrl("https://www.mudra.org.in")
                        .applicationMode("ONLINE")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(8)
                        .tags(List.of("Business", "Loan", "Mudra", "Startup"))
                        .viewCount(1560L)
                        .recommendationCount(920L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 5. PM Ujjwala Yojana
                Scheme.builder()
                        .schemeName("Pradhan Mantri Ujjwala Yojana (PMUY)")
                        .schemeCode("PMUY-LPG-005")
                        .shortDescription("Free LPG connection with ₹1,600 financial support for women in BPL households.")
                        .description("PMUY aims to safeguard the health of women and children by providing clean cooking fuel (LPG) connections to women from below poverty line households.")
                        .category("Energy & Utility")
                        .subcategory("LPG Connection")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(18)
                        .maximumAge(80)
                        .maximumIncome(new BigDecimal("200000"))
                        .allowedGenders(List.of("Female"))
                        .allowedCategories(List.of("SC", "ST", "OBC", "General"))
                        .allowedOccupations(List.of("ALL"))
                        .requiredDocuments(List.of("Aadhaar Card", "Ration Card", "BPL Card", "Bank Passbook"))
                        .benefits(List.of("Free LPG connection with first cylinder and stove free", "Deposit-free connection with ₹1,600 support per connection"))
                        .websiteUrl("https://www.pmuy.gov.in")
                        .applicationMode("OFFLINE")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(false)
                        .priority(7)
                        .tags(List.of("Women", "LPG", "Gas Connection", "BPL"))
                        .viewCount(740L)
                        .recommendationCount(480L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 6. National Scholarship Portal
                Scheme.builder()
                        .schemeName("National Means-cum-Merit Scholarship Scheme (NMMSS)")
                        .schemeCode("NSP-SCHOLARSHIP-006")
                        .shortDescription("Scholarship of ₹12,000 per annum for meritorious students from economically weaker sections.")
                        .description("NMMSS provides financial assistance to meritorious students of Class IX to XII to arrest their drop-out at class VIII and encourage them to continue education.")
                        .category("Education")
                        .subcategory("Student Scholarship")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(13)
                        .maximumAge(20)
                        .maximumIncome(new BigDecimal("350000"))
                        .allowedGenders(List.of("ALL"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("Student"))
                        .requiredDocuments(List.of("Aadhaar Card", "Income Certificate", "Mark Sheet", "School ID Card"))
                        .benefits(List.of("₹12,000 per annum (₹1,000 per month) directly credited to student bank account"))
                        .websiteUrl("https://scholarships.gov.in")
                        .applicationMode("ONLINE")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(8)
                        .tags(List.of("Education", "Scholarship", "Student", "Merit"))
                        .viewCount(1890L)
                        .recommendationCount(1100L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 7. Indira Gandhi National Old Age Pension Scheme (IGNOAPS)
                Scheme.builder()
                        .schemeName("Indira Gandhi National Old Age Pension Scheme (IGNOAPS)")
                        .schemeCode("NSAP-PENSION-007")
                        .shortDescription("Monthly pension of ₹500 to ₹1,000 for senior citizens below the poverty line.")
                        .description("IGNOAPS provides social security monthly pension to destitute elderly citizens aged 60 years and above belonging to BPL families.")
                        .category("Social Welfare")
                        .subcategory("Old Age Pension")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(60)
                        .maximumAge(110)
                        .maximumIncome(new BigDecimal("150000"))
                        .allowedGenders(List.of("ALL"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("ALL"))
                        .requiredDocuments(List.of("Aadhaar Card", "Age Proof Certificate", "BPL Certificate", "Bank Passbook"))
                        .benefits(List.of("₹500/month for age 60-79", "₹1,000/month for age 80+"))
                        .websiteUrl("https://nsap.nic.in")
                        .applicationMode("HYBRID")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(false)
                        .priority(7)
                        .tags(List.of("Pension", "Senior Citizen", "Old Age", "Social Welfare"))
                        .viewCount(620L)
                        .recommendationCount(390L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 8. Widow Pension Scheme
                Scheme.builder()
                        .schemeName("Indira Gandhi National Widow Pension Scheme (IGNWPS)")
                        .schemeCode("NSAP-WIDOW-008")
                        .shortDescription("Monthly financial pension support for destitute widows aged 40 years and above.")
                        .description("IGNWPS delivers social security pension support to widowed women living below the poverty line to ensure financial independence and dignity.")
                        .category("Social Welfare")
                        .subcategory("Widow Support")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(40)
                        .maximumAge(79)
                        .maximumIncome(new BigDecimal("150000"))
                        .allowedGenders(List.of("Female"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("ALL"))
                        .requiredDocuments(List.of("Aadhaar Card", "Husband Death Certificate", "BPL Ration Card", "Bank Account Passbook"))
                        .benefits(List.of("₹500 to ₹1,000 monthly direct pension transfer"))
                        .websiteUrl("https://nsap.nic.in")
                        .applicationMode("HYBRID")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(false)
                        .priority(6)
                        .tags(List.of("Widow", "Pension", "Women Empowerment"))
                        .viewCount(490L)
                        .recommendationCount(310L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 9. PMEGP
                Scheme.builder()
                        .schemeName("Prime Minister's Employment Generation Programme (PMEGP)")
                        .schemeCode("PMEGP-SUBSIDY-009")
                        .shortDescription("Credit-linked capital subsidy up to 35% for setting up micro-enterprises.")
                        .description("PMEGP is a major credit-linked subsidy scheme offering capital financial assistance for setting up new self-employment micro ventures in manufacturing and service sectors.")
                        .category("Business & Finance")
                        .subcategory("Capital Subsidy")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(18)
                        .maximumAge(65)
                        .allowedGenders(List.of("ALL"))
                        .allowedCategories(List.of("SC", "ST", "OBC", "Minorities", "Women", "General"))
                        .allowedOccupations(List.of("Unemployed", "Self-Employed", "Artisan", "Business Owner"))
                        .requiredDocuments(List.of("Aadhaar Card", "Project Proposal Report", "Educational Qualification Certificate", "Caste Certificate"))
                        .benefits(List.of("Subsidy up to 35% of project cost (Max project cost ₹50 Lakhs for Manufacturing)"))
                        .websiteUrl("https://www.kviconline.gov.in/pmegpeportal")
                        .applicationMode("ONLINE")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(8)
                        .tags(List.of("Employment", "Subsidy", "KVIC", "PMEGP", "Startup"))
                        .viewCount(1340L)
                        .recommendationCount(780L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 10. Stand-Up India
                Scheme.builder()
                        .schemeName("Stand-Up India Scheme")
                        .schemeCode("STANDUP-INDIA-010")
                        .shortDescription("Bank loans between ₹10 Lakhs and ₹1 Crore for SC/ST and Women entrepreneurs.")
                        .description("Stand-Up India facilitates bank loans between ₹10 Lakhs and ₹1 Crore to at least one SC/ST borrower and one woman borrower per bank branch for setting up a greenfield enterprise.")
                        .category("Business & Finance")
                        .subcategory("Entrepreneurship Loan")
                        .schemeType(SchemeType.CENTRAL)
                        .applicableStates(List.of("All India"))
                        .minimumAge(18)
                        .maximumAge(65)
                        .allowedGenders(List.of("Female", "ALL"))
                        .allowedCategories(List.of("SC", "ST", "ALL"))
                        .allowedOccupations(List.of("Entrepreneur", "Business Owner", "Self-Employed"))
                        .requiredDocuments(List.of("Aadhaar Card", "PAN Card", "Caste/Category Certificate", "Project Profile", "Company PAN/GST"))
                        .benefits(List.of("Loans between ₹10 Lakhs and ₹1 Crore for greenfield projects", "Repayable in 7 years with 18-month moratorium"))
                        .websiteUrl("https://www.standupmitra.in")
                        .applicationMode("ONLINE")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(9)
                        .tags(List.of("Women Entrepreneur", "SC/ST", "Bank Loan", "StandUp"))
                        .viewCount(1120L)
                        .recommendationCount(690L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 11. Tamil Nadu — Kalaignar Magalir Urimai Thittam
                Scheme.builder()
                        .schemeName("Kalaignar Magalir Urimai Thittam (KMUT)")
                        .schemeCode("TN-KMUT-011")
                        .shortDescription("Monthly rights grant of ₹1,000 to eligible women heads of households in Tamil Nadu.")
                        .description("KMUT provides a monthly financial assistance grant of ₹1,000 to women heads of families in Tamil Nadu to recognize their unpaid care work and improve livelihood security.")
                        .category("Social Welfare")
                        .subcategory("Women Grant")
                        .schemeType(SchemeType.STATE)
                        .applicableStates(List.of("Tamil Nadu"))
                        .minimumAge(21)
                        .maximumAge(70)
                        .maximumIncome(new BigDecimal("250000"))
                        .allowedGenders(List.of("Female"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("ALL"))
                        .requiredDocuments(List.of("Aadhaar Card", "Smart Ration Card", "Electricity Bill", "Bank Passbook"))
                        .benefits(List.of("₹1,000 monthly rights assistance directly into woman head's bank account"))
                        .websiteUrl("https://kmut.tn.gov.in")
                        .applicationMode("HYBRID")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(10)
                        .tags(List.of("Tamil Nadu", "Women", "KMUT", "Monthly Assistance"))
                        .viewCount(2450L)
                        .recommendationCount(1820L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 12. Tamil Nadu — Pudhumai Penn Scheme
                Scheme.builder()
                        .schemeName("Pudhumai Penn Scheme (Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme)")
                        .schemeCode("TN-PUDHUMAI-PENN-012")
                        .shortDescription("Monthly assistance of ₹1,000 for girl students pursuing higher education in Tamil Nadu.")
                        .description("Under Pudhumai Penn Scheme, financial assistance of ₹1,000 per month is provided to girl students who studied in Government schools from Class 6 to 12 until completion of degree/diploma.")
                        .category("Education")
                        .subcategory("Higher Education Grant")
                        .schemeType(SchemeType.STATE)
                        .applicableStates(List.of("Tamil Nadu"))
                        .minimumAge(17)
                        .maximumAge(25)
                        .allowedGenders(List.of("Female"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("Student"))
                        .requiredDocuments(List.of("Aadhaar Card", "Govt School TC / Certificate", "College Student ID", "Bank Account Details"))
                        .benefits(List.of("₹1,000 per month deposited directly until completion of graduation/diploma"))
                        .websiteUrl("https://penkalvi.tn.gov.in")
                        .applicationMode("ONLINE")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(9)
                        .tags(List.of("Tamil Nadu", "Girl Child", "Higher Education", "Student"))
                        .viewCount(1670L)
                        .recommendationCount(1050L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 13. Tamil Nadu — Naan Mudhalvan Scheme
                Scheme.builder()
                        .schemeName("Naan Mudhalvan Skill Development Scheme")
                        .schemeCode("TN-NAAN-MUDHALVAN-013")
                        .shortDescription("Flagship skill development and career guidance scheme for youth in Tamil Nadu.")
                        .description("Naan Mudhalvan aims to equip 10 Lakh youth across Tamil Nadu every year with technical skills, language proficiency, coding skills, and industry placement support.")
                        .category("Skill Development")
                        .subcategory("Career Training")
                        .schemeType(SchemeType.STATE)
                        .applicableStates(List.of("Tamil Nadu"))
                        .minimumAge(17)
                        .maximumAge(30)
                        .allowedGenders(List.of("ALL"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("Student", "Unemployed", "Job Seeker"))
                        .requiredDocuments(List.of("Aadhaar Card", "Educational Marksheet", "College ID Card"))
                        .benefits(List.of("Free high-end technical training modules", "Direct campus placement drives and industry mentorship"))
                        .websiteUrl("https://www.naanmudhalvan.tn.gov.in")
                        .applicationMode("ONLINE")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(true)
                        .priority(9)
                        .tags(List.of("Tamil Nadu", "Skill Development", "Placement", "Youth"))
                        .viewCount(1430L)
                        .recommendationCount(890L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build(),

                // 14. Tamil Nadu — Chief Minister's Comprehensive Health Insurance Scheme (CMCHIS)
                Scheme.builder()
                        .schemeName("Chief Minister's Comprehensive Health Insurance Scheme (CMCHIS)")
                        .schemeCode("TN-CMCHIS-014")
                        .shortDescription("Free cashless hospital care up to ₹5 Lakhs per family per year in Tamil Nadu.")
                        .description("CMCHIS provides cashless health insurance coverage to resident families of Tamil Nadu having annual income below ₹1.20 Lakhs per annum across government and private empanelled hospitals.")
                        .category("Healthcare")
                        .subcategory("State Health Insurance")
                        .schemeType(SchemeType.STATE)
                        .applicableStates(List.of("Tamil Nadu"))
                        .minimumAge(0)
                        .maximumAge(110)
                        .maximumIncome(new BigDecimal("120000"))
                        .allowedGenders(List.of("ALL"))
                        .allowedCategories(List.of("ALL"))
                        .allowedOccupations(List.of("ALL"))
                        .requiredDocuments(List.of("Aadhaar Card", "Smart Ration Card", "CMCHIS Smart Card", "Income Certificate"))
                        .benefits(List.of("Cashless treatment up to ₹5 Lakhs per family per year", "Covers specialized surgeries, cancer care, and organ transplants"))
                        .websiteUrl("https://www.cmchistn.com")
                        .applicationMode("HYBRID")
                        .status(SchemeStatus.PUBLISHED)
                        .featured(false)
                        .priority(8)
                        .tags(List.of("Tamil Nadu", "Health Insurance", "CMCHIS", "Hospital"))
                        .viewCount(980L)
                        .recommendationCount(640L)
                        .schemeVersion(1)
                        .lastUpdatedAt(LocalDateTime.now())
                        .lastUpdatedBy("system@schemebridge.gov.in")
                        .build()
        );

        schemeRepository.saveAll(seedSchemes);
        log.info("Successfully seeded {} realistic Government Schemes into MongoDB!", seedSchemes.size());
    }
}
