package com.schemebridge.adminservice.enums;

public enum AdminActionType {
    OFFICER_CREATED,
    OFFICER_UPDATED,
    OFFICER_STATUS_CHANGED,
    ROLE_ASSIGNED,
    ANNOUNCEMENT_CREATED,
    ANNOUNCEMENT_UPDATED,
    ANNOUNCEMENT_DELETED,
    FEEDBACK_RESOLVED,
    REPORT_GENERATED,
    SYSTEM_SETTING_UPDATED,
    FEATURE_FLAG_TOGGLED
}
