MERGE INTO ROLES t USING (
    SELECT 'USER' AS NAME, 'Standard citizen account' AS DESCRIPTION FROM DUAL UNION ALL
    SELECT 'ADMIN' AS NAME, 'Platform administrator' AS DESCRIPTION FROM DUAL UNION ALL
    SELECT 'VERIFICATION_OFFICER' AS NAME, 'Government verification officer' AS DESCRIPTION FROM DUAL UNION ALL
    SELECT 'SCHEME_MANAGER' AS NAME, 'Scheme administrator and manager' AS DESCRIPTION FROM DUAL
) s ON (t.NAME = s.NAME)
WHEN NOT MATCHED THEN
    INSERT (NAME, DESCRIPTION) VALUES (s.NAME, s.DESCRIPTION);
