-- Migration V9: Import existing user accounts and role mappings from local Oracle DB
-- Preserving user IDs to match MongoDB application and document records.

DELETE FROM REFRESH_TOKENS;
DELETE FROM USER_ROLES;
DELETE FROM USERS;

MERGE INTO USERS t USING (SELECT 'user@example.com' AS EMAIL, 'Test' AS FIRST_NAME, 'User' AS LAST_NAME, '$2a$10$msEGwApRNpIT4b8GgVxNQe5MAbYkro.pIlNNkaP2Lzx6KdUQc07Te' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 3 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'testuser01@gmail.com' AS EMAIL, 'Test' AS FIRST_NAME, 'User' AS LAST_NAME, '$2a$10$njWNc/GKWV0kwpk/HtkVMOCgJetuOyO6J.HQFL7luqEYSxgkHYUXW' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 4 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'manualotp01@example.com' AS EMAIL, 'Manual' AS FIRST_NAME, 'OTPTest' AS LAST_NAME, '$2a$10$ExMj8Vxo/R8/IBj54XpddOQgsMqqGCn0BwcMzqXo.v7ccjssVihxu' AS PASSWORD_HASH, '9876543211' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 8 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'otpattempt01@example.com' AS EMAIL, 'Attempt' AS FIRST_NAME, 'Test' AS LAST_NAME, '$2a$10$AbzVv9FbC7TCL1bjAu2zFOK4CExznj8o3nJ7ryJDKGUcayKluRGia' AS PASSWORD_HASH, '9876543212' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 9 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'otpfixed01@example.com' AS EMAIL, 'Attempt' AS FIRST_NAME, 'FixTest' AS LAST_NAME, '$2a$10$YVn7pzvXJCWy3vquExhN4OKj95R3W.TpTM6sPMCNWiqHbVoFVCCDC' AS PASSWORD_HASH, '9876543213' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 11 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'harden_user_20260824113108@example.com' AS EMAIL, 'Harden' AS FIRST_NAME, 'Tester' AS LAST_NAME, '$2a$10$PzhVSbNu9FSXBF2GeBndXO5bAchyZ5S2F8VylqzA4K4xNZjuHxkDS' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 22 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'verify_harden_20260824174622@example.com' AS EMAIL, 'Harden' AS FIRST_NAME, 'Verification' AS LAST_NAME, '$2a$10$eMivgfWZHflpyCt3gY4xxuT56e90/Ad7.y9TYxEZQSTUOQkgj5ObS' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 24 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'audit_user_20260824182319@example.com' AS EMAIL, 'Audit' AS FIRST_NAME, 'Citizen' AS LAST_NAME, '$2a$10$e3OxioC1w7rFx398zJQvwOlLKmrJFZyJLpt/rVY299m2TYF/JFzo6' AS PASSWORD_HASH, '9876543211' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 26 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'audit_runner_20260824182908@example.com' AS EMAIL, 'Audit' AS FIRST_NAME, 'Verification' AS LAST_NAME, '$2a$10$u8KTiV8eLt5POUtZil/PouEPaEG4gTn3GsKDJah7KwFGRohGV6RLC' AS PASSWORD_HASH, '9876543212' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 27 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'audit_runner_full_20260824183058@example.com' AS EMAIL, 'Audit' AS FIRST_NAME, 'Verification' AS LAST_NAME, '$2a$10$rXMdcGXGkYAd/bRBTUTcwOoM4wxpJqvPk3jrpSzkIvD7MUpFVkpla' AS PASSWORD_HASH, '9876543212' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 28 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'audit_phase3_citizen_20260825114629@example.com' AS EMAIL, 'Audit' AS FIRST_NAME, 'Citizen' AS LAST_NAME, '$2a$10$qMT.QWuU86V.hLosXfgLsOnfvhA5qEPQyCCLKVweJQWgVOx1fcYJC' AS PASSWORD_HASH, '9876543213' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 30 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizena_20260825114753@example.com' AS EMAIL, 'Test' AS FIRST_NAME, 'Citizen' AS LAST_NAME, '$2a$10$xI/DaujsZyo8iUFsQNx6/OG4XgrD1aZDGE2Hgc9fKRfGTifOAWZWe' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 31 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizenb_20260825114753@example.com' AS EMAIL, 'Test' AS FIRST_NAME, 'Citizen' AS LAST_NAME, '$2a$10$xDT9FsivaZp27RW6rZTub.5qYFc7QdSirhD1GgNSGoD1qDZBaBlx.' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 32 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'diag_test_20260825123047@example.com' AS EMAIL, 'Diagnostics' AS FIRST_NAME, 'TestUser' AS LAST_NAME, '$2a$10$jV9zf0YRbgBwXdp9oR.NJ.ZXkSZBo2NazuoDnfaKDnkLf8bSAvl/6' AS PASSWORD_HASH, '' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 33 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'diag_test_proxy_20260825123049@example.com' AS EMAIL, 'Diagnostics' AS FIRST_NAME, 'TestUser' AS LAST_NAME, '$2a$10$ypbWK3u2fXdPFZM6iIQ1EOaJxt/OFlD3uCO1reuUN6hVRwn3c8O6K' AS PASSWORD_HASH, '' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 34 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'fresh_citizen_20260825133706@example.com' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$38ouOqHiWa7TXRubOeMwveGyFJdnVI3z0Er/H0KcCvd7XxTDSHhgO' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 36 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'live_otp_audit_20260825150028@example.com' AS EMAIL, 'Priya' AS FIRST_NAME, 'Verma' AS LAST_NAME, '$2a$10$kPxbSMdQk2JIacW/hHzs4.IiJrOI3gwuwmhQKl4Nyya0fvfnxaw2y' AS PASSWORD_HASH, '9123456780' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 41 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_20260825152013@example.com' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$gGGyj9005wbGKJwBajexmOk6gS.GXtlwm3bd/B/wunx48bGUUxToe' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 46 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_b_20260825152013@example.com' AS EMAIL, 'Vikram' AS FIRST_NAME, 'Singh' AS LAST_NAME, '$2a$10$t9ygk725CqAj/xVisJ9S5OTLEzT9zOK1/PknFNrYEM4DtmJ.KYnjm' AS PASSWORD_HASH, '9876543211' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 47 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_20260825152046@example.com' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$jDseJ4MEfRhdfY7Y6NeFA.EVgz.vF.pUKtpx4eEMPF8uhuVmNLJEq' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 48 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_b_20260825152046@example.com' AS EMAIL, 'Vikram' AS FIRST_NAME, 'Singh' AS LAST_NAME, '$2a$10$ESWYmYss7Hq51DYJ/dn7Tujbvkdf0II/BMpdnl9fT33mvIMRKXfcq' AS PASSWORD_HASH, '9876543211' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 49 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_20260825152152@example.com' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$P0A4ELd6ehk6hDP2wqJETepOSujaGTLoXV21TvomfFVGfHVzLHw.y' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 50 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_b_20260825152152@example.com' AS EMAIL, 'Vikram' AS FIRST_NAME, 'Singh' AS LAST_NAME, '$2a$10$4C0jIuo1YUfZEIdaPaulueGk00fbc9.mUGjh3T7ElWH88dJNijili' AS PASSWORD_HASH, '9876543211' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 51 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'admin@schemebridge.gov.in' AS EMAIL, 'National' AS FIRST_NAME, 'Admin' AS LAST_NAME, '$2a$10$pEbNm2VbR64zZfJxCGxqKuzIpCPifG4VS4mrrOIR9cw299JAXT83W' AS PASSWORD_HASH, '9876543200' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 52 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen@schemebridge.gov.in' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$VtDiHLfzjuitlhYD5GsrHuAzacFx7lzA//PY2ktX1rJBl0hOGtx06' AS PASSWORD_HASH, '9876543201' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 53 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_1787729631311@schemebridge.gov.in' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$ZroNqh1TQoi530f4tWEniOgfJ3atEX7mC0bP.qqeZ5dBSKnpJ14Zy' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 62 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_1787729687852@schemebridge.gov.in' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$gyWhQki4KaQYE2KrgbNqT.1leSMfUEwSnvV2krJA5nZYP/C1aJU1W' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 63 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_1787729725789@schemebridge.gov.in' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$qKJnmmqZ/RLJy2AIj8Lvb.eJ6qIlNkCoJmFKf.4yZXKMKiQmFWcVe' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 64 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_1787729748203@schemebridge.gov.in' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$JJkn.jwnGBgPURG.mUxvee0nzyiLPHfhYw64fmPWp0IklYVT.vMVS' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 65 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_b_1787729748203@schemebridge.gov.in' AS EMAIL, 'Sunita' AS FIRST_NAME, 'Verma' AS LAST_NAME, '$2a$10$pipE2.040XQqQdcDv6hRz.rUozAPvVOBAdQg3JuIKrSjN4CzMhqQa' AS PASSWORD_HASH, '9876543211' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 66 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_1787729769586@schemebridge.gov.in' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$FR/XQ8MK.bnP/RZI.cZ6Ieo9bVN9uHn3/3yZvpXpVPiJypIth617.' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 67 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_b_1787729769586@schemebridge.gov.in' AS EMAIL, 'Sunita' AS FIRST_NAME, 'Verma' AS LAST_NAME, '$2a$10$VUvWw8faI9IZG65ciSiM3eQOEsWiQWtORkuBURZd6F4wdGB3l9tDe' AS PASSWORD_HASH, '9876543211' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 68 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'lathikakumar798@gmail.com' AS EMAIL, 'Lathika' AS FIRST_NAME, 'Kumar' AS LAST_NAME, '$2a$10$T/XIH5BRqGdi1YsJ.36P7eheZ5XnTSTba1haT/54GFhP0U75P9QmC' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 71 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_1787730951473@schemebridge.gov.in' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$/8yljAPn5q3Zv1COXhNSUulwYqaJ0QvAJRIEttCrkYcNgI918EYba' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 72 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_a_1787731447539@schemebridge.gov.in' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$dSWpK0Oseg1Kjhh7CmlWW.T/ka2XBx8rfCbvvNuwMH/Hfmefu9EI.' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 73 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT '717824i110@kce.ac.in' AS EMAIL, 'Arul' AS FIRST_NAME, 'P' AS LAST_NAME, '$2a$10$Uum5y4dGi5epF5U/rqkYY.8fdU11n5wLcm5IsUrRvPSXAk9I8I8Va' AS PASSWORD_HASH, '' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 74 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'test.citizen.1787739503504@schemebridge.in' AS EMAIL, 'Aakash' AS FIRST_NAME, 'Verma' AS LAST_NAME, '$2a$10$tlDf/RX137LdFNqiAGa0Ve9dh55b.3fh4DdfuN9tr/eDKr1KB1o4a' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 81 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'lathikaanti1@gmail.com' AS EMAIL, 'Lathika.K' AS FIRST_NAME, 'Lathika.K' AS LAST_NAME, '$2a$10$/WpcmIcG2CvYZnAooNGsyOmMUqYEoiBKGy6cotiUgnDU9SEGc8RA6' AS PASSWORD_HASH, '' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 82 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT '717824i132@kce.ac.in' AS EMAIL, 'Lathu' AS FIRST_NAME, 'Lathu' AS LAST_NAME, '$2a$10$YRirUhmjnP7m55SxuuMpyOcbjnA/D175MFq31SyuuUe30z1ue/LDe' AS PASSWORD_HASH, '' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 84 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'dharunnoob.l245@gmail.com' AS EMAIL, 'Dharun' AS FIRST_NAME, 'Dharun' AS LAST_NAME, '$2a$10$dV4160PcKog.zOZ7PFFWSuoAb4mo1kHFBt4KN7fAXTvwXGfr75dmy' AS PASSWORD_HASH, '7895259227' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 108 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'madhumithaps2006@gmail.com' AS EMAIL, 'Madhu' AS FIRST_NAME, 'Madhu' AS LAST_NAME, '$2a$10$bLmKqz5I3fZn57rUfgAXreBas.iYvrpGptNs5g1YDuD248J7boSFu' AS PASSWORD_HASH, '9894619419' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 181 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'verification.officer@schemebridge.gov.in' AS EMAIL, 'Verification' AS FIRST_NAME, 'Officer' AS LAST_NAME, '$2a$10$7TNxOC0ckc0iOJjTf8v2je8wi7dmVIVMpNW8JVxoeh77JLsRgFqg6' AS PASSWORD_HASH, '9876543202' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 205 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'scheme.manager@schemebridge.gov.in' AS EMAIL, 'Scheme' AS FIRST_NAME, 'Manager' AS LAST_NAME, '$2a$10$d4k9XWxoMgH2QCOaNmyeDOBELM.1JQwOpSUIXTffrEg6xMbqNhwo2' AS PASSWORD_HASH, '9876543203' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 206 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT '717824l103@kce.ac.in' AS EMAIL, 'Lathika.K' AS FIRST_NAME, 'Lathika.K' AS LAST_NAME, '$2a$10$uCpSVFFczrS8b1jhfT2VWuN29n07DSOqLE8oGlNNjKlDQqrPnHVIK' AS PASSWORD_HASH, '7904358845' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 232 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_dob_1789749573325@example.com' AS EMAIL, 'Lathika' AS FIRST_NAME, 'Kumar' AS LAST_NAME, '$2a$10$yapqoZeDi9Avu474no476O37gwhzs7.Z08Jv4U9G7u5yIfxYBSU6G' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 234 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_dob_1789749636530@example.com' AS EMAIL, 'Lathika' AS FIRST_NAME, 'Kumar' AS LAST_NAME, '$2a$10$eIpV9Vsiw8Xe4jrtRUxfEuVZqV6Q6me0WrzzDbWHQWEDpjIoGSyL2' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 235 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'citizen_dob_1789749693045@example.com' AS EMAIL, 'Lathika' AS FIRST_NAME, 'Kumar' AS LAST_NAME, '$2a$10$aTefAxQsJsC9st7G95BlgugikkMDX5dVbRN1aEPh0gb2K40Od0cui' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 236 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'priyayirp471@gmail.com' AS EMAIL, 'Priyadarshini' AS FIRST_NAME, 'P' AS LAST_NAME, '$2a$10$luNLH43dBj7/mqbatwfvzuBuKR1ZDfhLTl1HNAxYplgxRS7o12oam' AS PASSWORD_HASH, '7603842397' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 241 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT '717824i144@kce.ac.in' AS EMAIL, 'Nivetha' AS FIRST_NAME, 'N' AS LAST_NAME, '$2a$10$gxUzdYzSj63vX3Q48wDBd.p7epPKjHi2MCtx.VPQCYuoBaMZksjb.' AS PASSWORD_HASH, '8946524875' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 242 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT '717824v138@kce.ac.in' AS EMAIL, 'Manu' AS FIRST_NAME, 'Manu' AS LAST_NAME, '$2a$10$HvI.fBPMiZhWXDKTdqLt6erL86pBfVO0upLAimnGT45V4sxFpH8aC' AS PASSWORD_HASH, '9894619419' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 262 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'lathikakumar798+citizen@gmail.com' AS EMAIL, 'Citizen' AS FIRST_NAME, 'Verification' AS LAST_NAME, '$2a$10$IDqb6AWxZyxfqsgdBvjt.OnyfAwigz3h3SzQiryRkwhP9StbEKBwK' AS PASSWORD_HASH, '9876543210' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 264 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'lathikamagai496@gmail.com' AS EMAIL, 'Lathika.K' AS FIRST_NAME, 'Lathika.K' AS LAST_NAME, '$2a$10$x73kVBuPrnwwBEdsPPwM1uvEYSVX749TuQGOyKv2b7IA0FOPNpq8C' AS PASSWORD_HASH, '8946524875' AS PHONE_NUMBER, 'PENDING_VERIFICATION' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 268 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'lathikamangai496@gmail.com' AS EMAIL, 'Lathika.K' AS FIRST_NAME, 'Lathika.K' AS LAST_NAME, '$2a$10$uOs/4FtrspnR31I5qL1pMunIycCMY1u4ARE/hmfUiXJOCao0JCohG' AS PASSWORD_HASH, '9894619419' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 0 AS EMAIL_VERIFIED, 269 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USERS t USING (SELECT 'yaswanth1828@gmail.com' AS EMAIL, 'Yaswanth' AS FIRST_NAME, 'Yaswanth' AS LAST_NAME, '$2a$10$AnwtBMltBNPj71.Ta2lJl.3LeZzNZzEDwOuImkTIXiL8Ph4s/Xt8G' AS PASSWORD_HASH, '9894619419' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 270 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USER_ROLES t USING (SELECT 3 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 4 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 8 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 9 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 11 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 11 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'ADMIN') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 11 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'SCHEME_MANAGER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 22 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 24 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 26 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 27 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 28 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 30 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 31 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 32 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 33 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 34 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 36 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 41 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 46 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 47 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 48 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 49 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 50 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 51 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 52 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'ADMIN') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 53 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 62 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 63 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 64 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 65 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 66 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 67 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 68 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 71 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 72 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 73 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 74 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 81 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 82 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 84 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 108 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 181 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 205 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'VERIFICATION_OFFICER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 206 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'SCHEME_MANAGER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 232 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 234 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 235 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 236 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 241 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 242 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 262 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 264 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 268 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 269 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USER_ROLES t USING (SELECT 270 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

MERGE INTO USERS t USING (SELECT 'citizen@schemebridge.gov.in' AS EMAIL, 'Aarav' AS FIRST_NAME, 'Sharma' AS LAST_NAME, '$2a$10$VtDiHLfzjuitlhYD5GsrHuAzacFx7lzA//PY2ktX1rJBl0hOGtx06' AS PASSWORD_HASH, '9876543201' AS PHONE_NUMBER, 'ACTIVE' AS ACCOUNT_STATUS, 1 AS EMAIL_VERIFIED, 2 AS ID FROM DUAL) s ON (t.EMAIL = s.EMAIL) WHEN NOT MATCHED THEN INSERT (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD_HASH, PHONE_NUMBER, ACCOUNT_STATUS, EMAIL_VERIFIED) VALUES (s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PASSWORD_HASH, s.PHONE_NUMBER, s.ACCOUNT_STATUS, s.EMAIL_VERIFIED);

MERGE INTO USER_ROLES t USING (SELECT 2 AS USER_ID, r.ID AS ROLE_ID FROM ROLES r WHERE r.NAME = 'USER') s ON (t.USER_ID = s.USER_ID AND t.ROLE_ID = s.ROLE_ID) WHEN NOT MATCHED THEN INSERT (USER_ID, ROLE_ID) VALUES (s.USER_ID, s.ROLE_ID);

