package com.schemebridge.scheme.document;

public enum ApplicationEventType {
    APPLICATION_CREATED,
    DOCUMENT_UPLOADED,
    DOCUMENTS_PENDING,
    READY_FOR_SUBMISSION,
    APPLICATION_SUBMITTED,
    UNDER_REVIEW,
    APPROVED,
    REJECTED,
    CANCELLED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,
    DOCUMENT_STATUS_CHANGED,
    DOCUMENT_REUPLOAD_REQUIRED,
    CORRECTION_REQUIRED
}
