package com.schemebridge.scheme.document;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_UNDER_REVIEW,
    DOCUMENT_REJECTED,
    CORRECTION_REQUIRED,
    DOCUMENT_VERIFIED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_CANCELLED,
    GRIEVANCE_CREATED,
    GRIEVANCE_UPDATED,
    ADMIN_MESSAGE,
    SYSTEM_ALERT
}
